config/routes.rb
Rails.application.routes.draw do


  resources :categories do
    # then the listings are based on the category rather than a separate area
    resources :listings
  end

  # the homepage should be the categories controller, then the index action
  root "categories#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :listings

  validates :title, presence: true


end

app/models/listing.rb
class Listing < ApplicationRecord

  belongs_to :category

  validates :title, presence: true
  validates :body, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end


  def new
    @category = Category.new
  end

  def create
    @category = Category.new(form_params)

    if @category.save
     redirect_to category_path(@category)
   else
     render "new"
   end
 
  end

  def show
    @category = Category.find(params[:id])
  end

  def form_params
    params.require(:category).permit(:title)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController


  def new
    @category = Category.find(params[:category_id])
    @listing = @category.listings.new
  end

  def create

    @category = Category.find(params[:category_id])
    @listing = @category.listings.new(form_params)


    if @listing.save
     redirect_to category_path(@category)
    else
     render "new"
    end
  end

    def form_params
    # get the data from the form
    params.require(:listing).permit(:title, :body)
    end



  def show
    # individual review page
    @category = Category.find(params[:category_id])

    @listing = Listing.find(params[:id])
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :title %>
  <%= f.button :submit, "Add category" %>
<% end %>

app/views/categories/index.html.erb
<h2>All categories </h2>

<ul><% @categories.each do |category| %>

  <li>
    <%= link_to category.title, category_path(category) %>
  </li>
<% end %>

</ul>

<p><%= link_to "Add new category", new_category_path %></p>

app/views/categories/new.html.erb
<h3>Add your new category</h3>

<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<h2>Listings</h2>

<% @category.listings.each do |listing| %>
  <p><%= listing.title %></p>
<% end %>

<h3> Add a listing </h3>

<div>
  <%= link_to "New listing", new_category_listing_path(@category) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigslist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>
          <%= link_to "Craigslist", root_path %>
      </h1>


    </header>

    <%= yield %>
  </body>
</html>

app/views/listings/new.html.erb
<h3>Add your new listing</h3>

<%= simple_form_for [@category, @listing] do |f| %>

  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit, "Add listing" %>

<% end %>

app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>



<div>
  <%= simple_format @listing.description %>
</div>